### ISSUE TITLE
PTTd : push to talk delayed / Jingle short audio blurb 

### ISSUE THREAD

**Issue by TameOfGroans** [guardianproject/OSTel#1]
Similar to Jingle audio blurb but encrypted 

https://waze.uservoice.com/forums/59223-client-how-can-we-improve-waze-on-your-phone/suggestions/2997613-use-jingle-to-send-short-audio-blurbs-to-others

**Comment by TameOfGroans** [comment]
PTSd 

Push to send delayed

**Comment by lazzarello** [comment]
ostel is a realtime voice and video solution. PTT is not a supported feature.
