### ISSUE TITLE
  // , Windows Phone

### ISSUE THREAD

**Issue by v6** [guardianproject/OSTel#2]
// , 

I notice that Windows Phone has many applications for SIP and VOIP calls, but no instructions on the ostel.co website. 

Some family of mine have Windows Phones, but Signal, the app I prefer, does not offer an application for Windows Phones. 

Since I would like to offer them encrypted phone calls, I would like to use OSTEL for Windows Phones.

**Comment by n8fr8** [comment]
The apps must support ZRTP encryption. Do you have links so we can test?

**Comment by lazzarello** [comment]
closing due to staleness.
