### ISSUE TITLE
Ostel.co certificate expired

### ISSUE THREAD

**Issue by isavskyi** [guardianproject/OSTel#3]
@n8fr8

**Comment by n8fr8** [comment]
SSL Server Certificate
Issued To

Common Name (CN)    ostel.co
Organization (O)    <Not Part Of Certificate>
Organizational Unit (OU)    <Not Part Of Certificate>
Serial Number   47:8D:98:30:67:F0:39:8D:EE:46:9A:EE:6B:CB:CA:8D
Issued By

Common Name (CN)    RapidSSL SHA256 CA
Organization (O)    GeoTrust Inc.
Organizational Unit (OU)    <Not Part Of Certificate>
Validity Period

Issued On   Wednesday, April 6, 2016 at 8:00:00 PM
Expires On  Saturday, July 7, 2018 at 7:59:59 PM
Fingerprints

SHA-256 Fingerprint 00 95 8D 98 47 C8 68 F1 5C 39 C0 26 C7 0A AD 00
27 D3 B2 C5 E9 E4 F5 30 96 84 09 1E 90 27 40 BD
SHA-1 Fingerprint   C8 C9 CD FA E3 81 16 A9 55 D3 DF DD D3 1C 82 9D
A8 BC CE AE

**Comment by isavskyi** [comment]
See https://dev.guardianproject.info/issues/7487

The website's cert is fine, connecting via a client (Jitsi/Linphone) gets an old cert.

**Comment by n8fr8** [comment]
@lazzarello this one is for you!

**Comment by dalleas** [comment]
It's not possible to make calls or connect anymore. I'm getting a registration error. Readding the account didn't work.

**Comment by lazzarello** [comment]
This problem is resolved. The side effect I discovered was Linphone doesn't give certificate errors, so on my end, everything looked normal.
